import { useEffect, useState } from "react";
import axios from "axios";
const API = "http://localhost:3000";
const field = "mt-1 w-full rounded-xl border border-[var(--ed-border)] bg-[var(--ed-surface)] px-3 py-2.5";
const empty = { studentId: "", title: "", activities: "", difficulty: "easy", status: "assigned", dueDate: "", baselineScore: "", followUpScore: "", notes: "" };
export default function InterventionsView({ students, initialDraft }) {
  const [items, setItems] = useState([]); const [draft, setDraft] = useState(() => ({ ...empty, ...initialDraft })); const [editing, setEditing] = useState(null);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let mounted = true; axios.get(`${API}/interventions`).then((response) => { if (mounted) setItems(response.data); }).catch(() => { if (mounted) setError("Unable to load interventions."); }); return () => { mounted = false; }; }, []);
  const change = (key, value) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async (event) => {
    event.preventDefault(); if (busy) return; setBusy(true); setError(""); setMessage("");
    try {
      const body = { ...draft, baselineScore: draft.baselineScore === "" ? null : Number(draft.baselineScore), followUpScore: draft.followUpScore === "" ? null : Number(draft.followUpScore) };
      if (editing) await axios.put(`${API}/interventions/${editing}`, body); else await axios.post(`${API}/interventions`, body);
      setItems((await axios.get(`${API}/interventions`)).data); setEditing(null); setDraft(empty); setMessage("Intervention progress saved.");
    } catch (err) { setError(err.response?.data?.message || "Unable to save the intervention."); } finally { setBusy(false); }
  };
  return <div className="space-y-6">
    <section className="rounded-[22px] border border-[var(--ed-border)] bg-[var(--ed-surface)] p-6"><h2 className="text-xl font-bold">Track learning support</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">Assign practice, record completion, and compare baseline and follow-up percentages using comparable activities. You can copy practice from an AI insight and adapt it before assigning.</p>{error && <p role="alert" className="mt-4 text-[var(--ed-danger)]">{error}</p>}{message && <p role="status" className="mt-4">{message}</p>}
      <form onSubmit={save} className="mt-5 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Student<select aria-label="Intervention student" className={field} required disabled={Boolean(editing)} value={draft.studentId} onChange={(event) => change("studentId", event.target.value)}><option value="">Choose a student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}{editing && !students.some((student) => student.id === draft.studentId) && <option value={draft.studentId}>Archived student</option>}</select></label><label className="text-sm">Activity title<input required maxLength={200} className={field} value={draft.title} onChange={(event) => change("title", event.target.value)} /></label><label className="text-sm">Difficulty<select className={field} value={draft.difficulty} onChange={(event) => change("difficulty", event.target.value)}>{["easy", "medium", "hard"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Due date<input type="date" className={field} value={draft.dueDate} onChange={(event) => change("dueDate", event.target.value)} /></label><label className="text-sm">Progress<select className={field} value={draft.status} onChange={(event) => change("status", event.target.value)}><option value="assigned">Assigned</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label>{[["baselineScore", "Baseline (%)"], ["followUpScore", "Follow-up (%)"]].map(([key, label]) => <label key={key} className="text-sm">{label}<input type="number" min="0" max="100" step="0.1" className={field} value={draft[key]} onChange={(event) => change(key, event.target.value)} /></label>)}</div><label className="block text-sm">Practice activities<textarea required rows={5} maxLength={5000} className={field} value={draft.activities} onChange={(event) => change("activities", event.target.value)} /></label><label className="block text-sm">Teacher notes / next steps<textarea rows={3} maxLength={2000} className={field} value={draft.notes} onChange={(event) => change("notes", event.target.value)} /></label><div className="flex gap-3"><button disabled={busy} className="rounded-xl bg-[var(--ed-primary)] px-5 py-3 font-semibold text-white disabled:opacity-50">{editing ? "Save progress" : "Assign intervention"}</button>{editing && <button type="button" disabled={busy} onClick={() => { setEditing(null); setDraft(empty); }} className="rounded-xl border border-[var(--ed-border)] px-4 py-3">Cancel</button>}</div></form>
    </section>
    <section className="space-y-3"><h2 className="text-xl font-bold">Assigned activities</h2>{items.map((item) => <article key={item._id} className="rounded-2xl border border-[var(--ed-border)] bg-[var(--ed-surface)] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{item.title}</h3><p className="mt-1 text-sm text-[var(--ed-muted)]">{item.studentId?.name ?? "Student unavailable"} · {item.difficulty} · {item.status.replaceAll("_", " ")}{item.dueDate && ` · Due ${new Date(item.dueDate).toLocaleDateString()}`}</p></div><button disabled={busy} className="text-sm font-semibold text-[var(--ed-accent-text)]" onClick={() => { setEditing(item._id); setDraft({ ...empty, ...item, studentId: item.studentId?._id ?? "", dueDate: item.dueDate?.slice(0,10) ?? "", baselineScore: item.baselineScore ?? "", followUpScore: item.followUpScore ?? "" }); }}>Update progress</button></div><p className="mt-3 whitespace-pre-wrap text-sm">{item.activities}</p><p className="mt-3 text-sm">Baseline: {item.baselineScore ?? "Not recorded"} · Follow-up: {item.followUpScore ?? "Not recorded"}{typeof item.baselineScore === "number" && typeof item.followUpScore === "number" && ` · Change: ${(item.followUpScore - item.baselineScore).toFixed(1)} points`}</p>{item.notes && <p className="mt-2 whitespace-pre-wrap text-sm text-[var(--ed-muted)]">{item.notes}</p>}</article>)}{!items.length && <p className="text-sm text-[var(--ed-muted)]">No interventions assigned in this school year.</p>}</section>
  </div>;
}
