import { useEffect, useState } from "react";
import axios from "axios";
const API = "http://localhost:3000";
const field = "mt-1 w-full rounded-xl border border-[var(--ed-border)] bg-[var(--ed-surface)] px-3 py-2.5";
const button = "rounded-xl bg-[var(--ed-primary)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50";
const box = "rounded-[22px] border border-[var(--ed-border)] bg-[var(--ed-surface)] p-6";
export default function TeacherSettings() {
  const [years, setYears] = useState([]); const [active, setActive] = useState(""); const [yearName, setYearName] = useState("");
  const [rules, setRules] = useState(null); const [events, setEvents] = useState([]);
  const [password, setPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [recovery, setRecovery] = useState("");
  const [backup, setBackup] = useState(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const refresh = async () => { const [y, r, h] = await Promise.all([axios.get(`${API}/school-years`), axios.get(`${API}/grading-rules`), axios.get(`${API}/change-history`)]); setYears(y.data.years); setActive(y.data.activeId ?? ""); setRules(r.data); setEvents(h.data); };
  useEffect(() => { let mounted = true; Promise.all([axios.get(`${API}/school-years`), axios.get(`${API}/grading-rules`), axios.get(`${API}/change-history`)]).then(([y, r, h]) => { if (!mounted) return; setYears(y.data.years); setActive(y.data.activeId ?? ""); setRules(r.data); setEvents(h.data); }).catch((err) => { if (mounted) setError(err.response?.data?.message || "Unable to load teacher settings."); }); return () => { mounted = false; }; }, []);
  const run = async (action) => { if (busy) return; setBusy(true); setMessage(""); setError(""); try { await action(); } catch (err) { setError(err.response?.data?.message || err.message || "Unable to complete the action."); } finally { setBusy(false); } };
  const signOut = () => { localStorage.removeItem("eduliteToken"); localStorage.removeItem("user"); window.location.assign("/"); };
  const download = (value, filename) => { const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: "application/json" })); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6">
    {error && <p role="alert" className="rounded-xl bg-[var(--ed-danger-soft)] p-4 text-[var(--ed-danger)]">{error}</p>}{message && <p role="status" className="rounded-xl bg-[var(--ed-accent-soft)] p-4">{message}</p>}
    <section className={box}><h2 className="text-xl font-bold">School years</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">Student enrollments, assessments, scores, interventions, and awards stay separate for each year. Sections and subject names are reusable. Existing data stays in Legacy until you assign it.</p>
      <label className="mt-4 block text-sm">Active school year<select aria-label="Active school year" className={field} value={active} disabled={busy} onChange={(event) => setActive(event.target.value)}>{years.map((year) => <option key={year._id ?? "legacy"} value={year._id ?? ""}>{year.name}</option>)}</select></label>
      <button type="button" className={`${button} mt-3`} disabled={busy} onClick={() => run(async () => { await axios.put(`${API}/school-years/active`, { id: active || null }); window.location.reload(); })}>Open school year</button>
      <form className="mt-5 flex flex-wrap gap-3" onSubmit={(event) => { event.preventDefault(); run(async () => { await axios.post(`${API}/school-years`, { name: yearName }); setYearName(""); await refresh(); setMessage("School year created. Choose it above to begin."); }); }}><input aria-label="New school year" className={`${field} max-w-xs`} required maxLength={40} placeholder="e.g. 2026–2027" value={yearName} onChange={(event) => setYearName(event.target.value)} /><button disabled={busy} className={button}>Create school year</button></form>
      {active && <button type="button" className="mt-4 rounded-xl border border-[var(--ed-border)] px-4 py-3 text-sm" disabled={busy} onClick={() => run(async () => { if (!window.confirm("Move all unassigned academic records into this school year? The destination must be empty.")) return; await axios.post(`${API}/school-years/assign-legacy`, { id: active }); window.location.reload(); })}>Assign legacy records to selected year</button>}
    </section>
    {rules && <form className={box} onSubmit={(event) => { event.preventDefault(); run(async () => { const response = await axios.put(`${API}/grading-rules`, rules); setMessage(response.data.message); window.location.reload(); }); }}><h2 className="text-xl font-bold">Grading & promotion rules</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">Rules apply to the active school year. Component weights must total 100%. The existing ECR transmutation and examination split remain in use.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{[['passingGrade', 'Passing grade'], ['highPerformingGrade', 'High-performing grade'], ['writtenWorkWeight', 'Written work weight (%)'], ['performanceTaskWeight', 'Performance task weight (%)'], ['examinationWeight', 'Examination weight (%)']].map(([key, label]) => <label key={key} className="text-sm">{label}<input required type="number" min="0" max="100" step="0.1" className={field} value={rules[key]} onChange={(event) => setRules((current) => ({ ...current, [key]: event.target.value === "" ? "" : Number(event.target.value) }))} /></label>)}</div><div className="mt-4 space-y-3">{[['requireAllSubjectsPassing', 'Require every subject to pass for promotion (otherwise use the overall final average)'], ['requireCompleteScores', 'Require every created assessment score before finishing a student']].map(([key, label]) => <label key={key} className="flex gap-3 text-sm"><input type="checkbox" checked={rules[key]} onChange={(event) => setRules((current) => ({ ...current, [key]: event.target.checked }))} />{label}</label>)}</div><button className={`${button} mt-5`} disabled={busy}>Save rules</button></form>}
    <section className={box}><h2 className="text-xl font-bold">Account security</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">A private, one-use recovery code lets you reset a forgotten password. Save it outside EduLITE. Sign-in sessions expire after eight hours.</p><label className="mt-4 block text-sm">Current password<input autoComplete="current-password" type="password" className={field} value={password} onChange={(event) => setPassword(event.target.value)} /></label><div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={busy || !password} onClick={() => run(async () => { const response = await axios.post(`${API}/account/recovery-code`, { password }); setRecovery(response.data.recoveryCode); setPassword(""); setMessage(response.data.message); })}>Generate recovery code</button><button className={button} disabled={busy} onClick={() => run(async () => { await axios.post(`${API}/account/sign-out-all`); signOut(); })}>Sign out all sessions</button></div>{recovery && <div className="mt-4 rounded-xl bg-[var(--ed-subtle)] p-4"><p className="text-sm font-semibold">Save this code now. It is only displayed here once.</p><code className="mt-2 block break-all select-all">{recovery}</code><button type="button" className="mt-3 text-sm underline" onClick={() => { download({ recoveryCode: recovery }, "edulite-private-recovery-code.json"); }}>Download private code</button><button type="button" className="ml-4 text-sm underline" onClick={() => setRecovery("")}>Hide code</button></div>}<form className="mt-5" onSubmit={(event) => { event.preventDefault(); run(async () => { await axios.post(`${API}/account/change-password`, { password, new_password: newPassword }); signOut(); }); }}><label className="block text-sm">New password<input type="password" autoComplete="new-password" minLength={8} required className={field} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><button className={`${button} mt-3`} disabled={busy || !password}>Change password & sign out</button></form></section>
    <section className={box}><h2 className="text-xl font-bold">Backups & recovery</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">Download your records for all school years, including archives, awards, interventions, and history. Account passwords and recovery codes are excluded. Keep backups private. Restoring adds separate copies; it preserves existing records.</p><button type="button" className={`${button} mt-4`} disabled={busy} onClick={() => run(async () => { const response = await axios.get(`${API}/backups`); download(response.data, `edulite-backup-${new Date().toISOString().slice(0,10)}.json`); })}>Download backup</button><form className="mt-5 space-y-3" onSubmit={(event) => { event.preventDefault(); run(async () => { const response = await axios.post(`${API}/backups/restore`, { password, backup }); setMessage(response.data.message); setBackup(null); setPassword(""); await refresh(); }); }}><input aria-label="Backup file" type="file" accept=".json,application/json" onChange={(event) => run(async () => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 20 * 1024 * 1024) throw new Error("Choose a backup of at most 20 MB."); setBackup(JSON.parse(await file.text())); })} /><p className="text-xs text-[var(--ed-muted)]">Enter your current password in Account security above to authorize restore.</p><button className={button} disabled={busy || !backup || !password}>Restore backup as separate records</button></form></section>
    <section className={box}><h2 className="text-xl font-bold">Change history</h2><p className="mt-2 text-sm text-[var(--ed-muted)]">Recent activity for your account, including score edits and archive decisions.</p><button className="mt-3 text-sm underline" type="button" onClick={() => run(refresh)} disabled={busy}>Refresh history</button><div className="mt-4 max-h-96 space-y-3 overflow-auto">{events.map((event) => <details key={event._id} className="rounded-xl border border-[var(--ed-border)] p-3"><summary className="cursor-pointer text-sm">{event.actorName ?? "Teacher"} · {event.action} · {event.resource} · {new Date(event.createdAt).toLocaleString()}</summary><div className="mt-3 space-y-2 text-sm">{Array.isArray(event.before) && event.before.map((record, index) => <p key={index}>{record.name ?? "Previous record"}{typeof record.score === "number" && ` · Score: ${record.score}`}{typeof record.grade === "number" && ` · Grade level: ${record.grade}`}</p>)}<dl className="grid grid-cols-2 gap-2">{Object.entries(event.changes?.$set ?? event.changes ?? {}).filter(([key]) => !["ownerId", "_id", "__v", "pdfData", "schoolYearId", "subjectIds", "assessmentId", "studentId", "sectionId", "previousEnrollmentId"].includes(key)).map(([key, value]) => <div key={key}><dt className="text-xs text-[var(--ed-muted)]">{({ score: "Recorded score", name: "Name", grade: "Grade level", archived: "Archived", title: "Activity / award", status: "Progress", outcome: "Teacher decision", schoolYear: "School year", passingGrade: "Passing grade", highPerformingGrade: "High-performing grade", baselineScore: "Baseline (%)", followUpScore: "Follow-up (%)" })[key] ?? key.replace(/([A-Z])/g, " $1")}</dt><dd className="break-words">{value === null ? "Not recorded" : typeof value === "boolean" ? value ? "Yes" : "No" : typeof value === "object" ? Array.isArray(value) ? `${value.length} records` : "Updated details" : String(value)}</dd></div>)}</dl></div></details>)}{!events.length && <p className="text-sm text-[var(--ed-muted)]">No changes have been recorded yet.</p>}</div></section>
  </div>;
}
