import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import express from "express";
import mongoose from "mongoose";
import jwt from "jsonwebtoken";
import Student from "../models/Student.js";
import User from "../models/User.js";
import Subject from "../models/Subject.js";
import Assessment from "../models/Assessment.js";
import AssessmentScore from "../models/AssessmentScore.js";
import SchoolYear from "../models/SchoolYear.js";
import Intervention from "../models/Intervention.js";
import StudentAiInsight from "../models/StudentAiInsight.js";
import lifecycleRouter from "../studentLifecycle.js";
import { classifyYearEnd, validateFinishDecision } from "../utils/yearEnd.js";

const subject = (name, finalGrade, isFullyComplete = true) => ({ name, final: { finalGrade, isFullyComplete } });
test("year-end readiness requires complete passing grades in every subject", () => {
  assert.equal(classifyYearEnd([subject("Math", 75), subject("Science", 90)]).status, "ready");
  const failed = classifyYearEnd([subject("Math", 74), subject("Science", 99)]);
  assert.equal(failed.status, "intervention");
  assert.deepEqual(failed.failedSubjects, ["Math"]);
  assert.equal(classifyYearEnd([subject("Math", 99, false)]).status, "pending");
  assert.equal(classifyYearEnd([subject("Math", null)]).status, "pending");
  assert.equal(classifyYearEnd([]).status, "pending");
  assert.equal(validateFinishDecision(failed, { school_year: "2026–2027", outcome: "graduated" }), "Students with failing subjects need further intervention before promotion or graduation.");
  assert.equal(validateFinishDecision(failed, { school_year: "2026–2027", outcome: "intervention" }), null);
  assert.ok(validateFinishDecision(classifyYearEnd([]), { school_year: "2026–2027", outcome: "promoted" }));
});

test("student queries hide archives by default and allow explicit history reads", async (t) => {
  const seen = [];
  t.mock.method(Student.collection, "find", (filter) => { seen.push(filter); return { toArray: async () => [] }; });
  await Student.find({ ownerId: new mongoose.Types.ObjectId() }).lean();
  assert.deepEqual(seen[0].archived, { $ne: true });
  await Student.find({ archived: true }).setOptions({ includeArchived: true }).lean();
  assert.equal(seen[1].archived, true);
});

const query = (value) => ({ populate() { return this; }, sort() { return this; }, select() { return this; }, setOptions() { return this; }, lean: async () => value, then(resolve, reject) { return Promise.resolve(value).then(resolve, reject); } });
test("HTTP year-end review and finishing preserve records and enforce teacher scope", async (t) => {
  const originalSecret = process.env.JWT_SECRET;
  process.env.JWT_SECRET = "year-end-local-test-secret";
  t.after(() => { if (originalSecret === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = originalSecret; });
  const owner = new mongoose.Types.ObjectId();
  const id = new mongoose.Types.ObjectId();
  const subjectId = new mongoose.Types.ObjectId();
  const foreignId = new mongoose.Types.ObjectId();
  let archived = false;
  let snapshot;
  let scoreValue = 10;
  let missing = false;
  const assessments = [1, 2, 3].flatMap((term) => [
    ["written_work", 1], ["performance_task", 1], ["summative_test", 1], ["summative_test", 2], ["term_exam", 1],
  ].map(([category, sequence]) => ({ _id: new mongoose.Types.ObjectId(), subjectId, term, category, sequence, totalItems: 10, name: `${category} ${term}`, date: new Date(), budgetOfWork: "Fractions" })));
  const filters = [];
  t.mock.method(User, "findById", () => query({ _id: owner, name: "Teacher" }));
  t.mock.method(Student, "find", (filter) => {
    assert.equal(String(filter.ownerId), String(owner));
    if (filter.archived === true) return query(archived ? [{ _id: id, archiveSnapshot: snapshot, archivedAt: snapshot.archivedAt }] : []);
    return query(!archived && (!filter._id || String(filter._id) === String(id)) ? [{ _id: id, name: "Alice", grade: 7, sectionId: { name: "Rose" }, subjectIds: [subjectId] }] : []);
  });
  t.mock.method(Student, "findOne", (filter) => query(filter.archived !== true && !archived && String(filter._id) === String(id) ? { _id: id, name: "Alice", grade: 7, sectionId: new mongoose.Types.ObjectId(), subjectIds: [subjectId], schoolYearId: null } : archived && String(filter._id) === String(id) && String(filter.ownerId) === String(owner) ? { archiveSnapshot: snapshot } : null));
  t.mock.method(Subject, "find", () => query([{ _id: subjectId, name: "Mathematics" }]));
  t.mock.method(Assessment, "find", () => query(assessments));
  t.mock.method(AssessmentScore, "find", () => query(assessments.filter((_assessment, index) => !missing || index > 0).map((assessment) => ({ studentId: id, assessmentId: assessment._id, score: scoreValue }))));
  t.mock.method(Intervention, "find", () => query([]));
  t.mock.method(StudentAiInsight, "find", () => query([{ title: "Practice fractions", result: { plan: { overview: "Target fractions" } } }]));
  t.mock.method(Student, "findOneAndUpdate", async (filter, update) => { filters.push(filter); if (update.$set.archiveSnapshot) snapshot = update.$set.archiveSnapshot; archived = update.$set.archived; return { _id: id, schoolYearId: null }; });
  const app = express(); app.use(express.json(), lifecycleRouter);
  const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
  t.after(() => new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); }));
  const url = `http://127.0.0.1:${server.address().port}`;
  const authorization = `Bearer ${jwt.sign({ sub: String(owner) }, process.env.JWT_SECRET, { issuer: "edulite-api", audience: "edulite-frontend" })}`;
  const request = (path, body) => fetch(url + path, { method: body ? "POST" : "GET", headers: { authorization, "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal((await fetch(url + "/year-end-report")).status, 401);
  const report = await (await request("/year-end-report")).json();
  assert.equal(report[0].status, "ready");
  assert.equal(report[0].subjects[0].assessments.length, 15);
  const decision = { school_year: "2026–2027", outcome: "graduated", notes: "Completed all subjects." };
  assert.equal((await request(`/students/${foreignId}/finish`, decision)).status, 404);
  missing = true;
  assert.equal((await request(`/students/${id}/finish`, decision)).status, 400);
  missing = false; scoreValue = 0;
  assert.equal((await request(`/students/${id}/finish`, decision)).status, 400);
  scoreValue = 10;
  assert.equal((await request(`/students/${id}/finish`, { ...decision, school_year: "" })).status, 400);
  assert.equal(filters.length, 0);
  assert.equal((await request(`/students/${id}/finish`, decision)).status, 200);
  assert.equal(String(filters[0].ownerId), String(owner));
  assert.deepEqual(filters[0].archived, { $ne: true });
  assert.equal(snapshot.subjects[0].assessments[0].score, 10);
  assert.equal(snapshot.subjects[0].assessments[0].budgetOfWork, "Fractions");
  assert.equal(snapshot.insights[0].title, "Practice fractions");
  assert.equal(snapshot.grade, 7);
  assert.equal(snapshot.outcome, "graduated");
  assert.deepEqual(await (await request("/year-end-report")).json(), []);
  assert.equal((await (await request("/student-archives")).json()).length, 1);
  const detail = await (await request(`/student-archives/${id}`)).json();
  assert.equal(detail.notes, decision.notes);
  assert.equal(detail.subjects[0].final.finalGrade, 100);
  assert.equal((await request(`/student-archives/${foreignId}`)).status, 404);
  assert.equal((await request(`/students/${id}/finish`, decision)).status, 404);
  assert.equal((await request(`/student-archives/${id}/restore`, { restore: true })).status, 200);
  assert.equal((await (await request("/year-end-report")).json()).length, 1);
  const nextYearId = new mongoose.Types.ObjectId();
  t.mock.method(SchoolYear, "findOne", () => query({ _id: nextYearId, ownerId: owner, name: "2027–2028" }));
  const enrollments = [];
  t.mock.method(Student, "create", async (docs) => { enrollments.push(...docs); return [{ _id: new mongoose.Types.ObjectId() }]; });
  t.mock.method(mongoose.connection, "transaction", async (work) => work({}));
  assert.equal((await request(`/students/${id}/finish`, { ...decision, outcome: "promoted", next_year_id: String(nextYearId) })).status, 200);
  assert.equal(enrollments.length, 1);
  assert.equal(enrollments[0].grade, 8);
  assert.equal(String(enrollments[0].schoolYearId), String(nextYearId));
  assert.equal(String(enrollments[0].previousEnrollmentId), String(id));
  assert.ok(snapshot.nextEnrollmentId);
});
